from __future__ import annotations

import csv
import hashlib
import json
import time
from pathlib import Path
from tempfile import TemporaryDirectory
from uuid import UUID, uuid4

import typer
from rich.console import Console

from helis.agent_spec_domain import AgentMemoryScope, AgentSpecBundle, ChildAgentSpec
from helis.agent_spec_store import AgentSpecStore
from helis.bot_architect import architecture_input_hash
from helis.budget import CycleBudget
from helis.child_agent_factory import ChildAgentFactory
from helis.child_agent_runtime import ChildAgentRuntime
from helis.child_agent_store import ChildAgentArtifactStore
from helis.child_agent_worker import ChildAgentWorker
from helis.domain import Opportunity, ValidationOutcome, ValidationResult, VentureStage
from helis.engine import HelisEngine
from helis.model_provider import OpenAICompatibleProvider
from helis.store import HelisStore
from helis.venture_architecture_domain import (
    CapabilityImplementation,
    CapabilityNode,
    VentureArchitecture,
)
from helis.venture_architecture_store import VentureArchitectureStore

app = typer.Typer(help="Materialize, run and operate venture-owned agents generated by HELIS")
console = Console()


def _engine(db: Path) -> HelisEngine:
    return HelisEngine(HelisStore(db))


def _worker(
    engine: HelisEngine,
    artifact_id: UUID,
    workspace_root: Path,
    *,
    max_model_calls: int = 4,
) -> ChildAgentWorker:
    return ChildAgentWorker(
        engine,
        OpenAICompatibleProvider.from_env(),
        artifact_id,
        workspace_root=workspace_root,
        max_model_calls_per_job=max_model_calls,
    )


def _enqueue_csv(worker: ChildAgentWorker, input_csv: Path) -> int:
    raw = input_csv.read_bytes()
    file_hash = hashlib.sha256(raw).hexdigest()
    count = 0
    with input_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise ValueError("CSV must contain a header row")
        for row_number, row in enumerate(reader, start=2):
            normalized = {str(key): str(value or "") for key, value in row.items() if key is not None}
            task = (
                "Process this supplied record according to your immutable child-agent contract.\n"
                "RECORD:\n"
                + json.dumps(normalized, ensure_ascii=False, sort_keys=True)
            )
            worker.enqueue(
                task,
                source="csv",
                source_key=f"{file_hash}:{row_number}",
                metadata={"file": input_csv.name, "row": str(row_number)},
            )
            count += 1
    return count


def _print_receipt(receipt) -> None:
    console.print(
        f"job={receipt.job_id} status={receipt.status.value} turns={receipt.turns_used} "
        f"stop={receipt.stop_reason}"
    )
    if receipt.output:
        console.print(receipt.output)


@app.command()
def materialize(
    opportunity_id: str,
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    """Materialize immutable child-agent artifacts from a generated venture spec bundle."""
    engine = _engine(db)
    report = ChildAgentFactory(engine, workspace_root=workspace_root).materialize_if_needed(
        UUID(opportunity_id)
    )
    if report.blocked_reason is not None:
        console.print(f"[red]blocked[/]: {report.blocked_reason}")
        raise typer.Exit(code=1)
    console.print(
        f"venture={report.opportunity_id} agents={len(report.artifacts)} "
        f"created={report.created_count}"
    )
    for artifact in report.artifacts:
        console.print(
            f"- {artifact.id} capability={artifact.capability_key} "
            f"hash={artifact.artifact_hash[:12]}… path={artifact.manifest_path}"
        )


@app.command("list")
def list_agents(opportunity_id: str, db: Path = Path("helis.db")) -> None:
    """List generated child-agent artifacts without model or network calls."""
    engine = _engine(db)
    artifacts = ChildAgentArtifactStore(engine.store).list(UUID(opportunity_id))
    if not artifacts:
        console.print("no child agents")
        return
    for artifact in artifacts:
        console.print(
            f"{artifact.id} capability={artifact.capability_key} status={artifact.status.value} "
            f"hash={artifact.artifact_hash[:12]}…"
        )


@app.command()
def run(
    artifact_id: str,
    task: str = typer.Option(..., help="Task inside this generated capability contract"),
    max_model_calls: int = typer.Option(4, min=1, max=12),
    max_tokens: int = typer.Option(12_000, min=1),
    max_model_cost_cents: float = typer.Option(5.0, min=0),
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    """Run one generated immutable child agent immediately."""
    engine = _engine(db)
    budget = CycleBudget(
        max_model_calls=max_model_calls,
        max_tokens=max_tokens,
        max_cost_cents=max_model_cost_cents,
    )
    result = ChildAgentRuntime(
        engine,
        OpenAICompatibleProvider.from_env(),
        budget,
        workspace_root=workspace_root,
    ).run(UUID(artifact_id), task)
    console.print(
        f"status={result.status.value} turns={result.turns_used} stop={result.stop_reason}"
    )
    console.print(result.output)
    console.print(f"run={result.id} path={result.run_path}")


@app.command()
def enqueue(
    artifact_id: str,
    task: str = typer.Option(..., help="Work item for this generated child agent"),
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    engine = _engine(db)
    job = _worker(engine, UUID(artifact_id), workspace_root).enqueue(task)
    console.print(f"enqueued job={job.id} task_hash={job.task_hash[:12]}…")


@app.command("enqueue-file")
def enqueue_file(
    artifact_id: str,
    input_file: Path,
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    raw = input_file.read_text(encoding="utf-8")
    task = f"Process this supplied work record according to your contract.\nRECORD:\n{raw}"
    source_key = hashlib.sha256(input_file.read_bytes()).hexdigest()
    engine = _engine(db)
    job = _worker(engine, UUID(artifact_id), workspace_root).enqueue(
        task,
        source="file",
        source_key=source_key,
        metadata={"file": input_file.name},
    )
    console.print(f"enqueued job={job.id} source={input_file}")


@app.command("enqueue-csv")
def enqueue_csv(
    artifact_id: str,
    input_csv: Path,
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    engine = _engine(db)
    worker = _worker(engine, UUID(artifact_id), workspace_root)
    count = _enqueue_csv(worker, input_csv)
    console.print(f"queued_rows={count} pending={worker.pending_count()}")


@app.command()
def work(
    artifact_id: str,
    watch: bool = typer.Option(False, help="Keep watching the generated agent queue"),
    poll_seconds: float = typer.Option(2.0, min=0.2, max=60),
    max_jobs: int = typer.Option(100, min=1, max=10_000),
    max_model_calls: int = typer.Option(4, min=1, max=12),
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    engine = _engine(db)
    worker = _worker(
        engine,
        UUID(artifact_id),
        workspace_root,
        max_model_calls=max_model_calls,
    )
    processed = 0
    try:
        while True:
            receipts = worker.work_until_empty(max_jobs=max_jobs - processed)
            for receipt in receipts:
                _print_receipt(receipt)
            processed += len(receipts)
            if processed >= max_jobs or not watch:
                break
            if not receipts:
                time.sleep(poll_seconds)
    except KeyboardInterrupt:
        console.print("worker stopped")
    console.print(f"processed={processed} pending={worker.pending_count()}")


@app.command()
def results(
    artifact_id: str,
    limit: int = typer.Option(20, min=1, max=1000),
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    engine = _engine(db)
    worker = _worker(engine, UUID(artifact_id), workspace_root)
    result_dir = worker.queue_root / "results"
    paths = sorted(result_dir.glob("*.json"), key=lambda path: path.stat().st_mtime, reverse=True)
    for path in paths[:limit]:
        receipt = worker.receipt(UUID(path.stem))
        if receipt is not None:
            _print_receipt(receipt)


@app.command("recover-jobs")
def recover_jobs(
    artifact_id: str,
    older_than_minutes: int = typer.Option(60, min=1),
    workspace_root: Path = Path(".helis/ventures"),
    db: Path = Path("helis.db"),
) -> None:
    engine = _engine(db)
    worker = _worker(engine, UUID(artifact_id), workspace_root)
    recovered = worker.recover_stale_processing(older_than_minutes=older_than_minutes)
    console.print(f"recovered={recovered} pending={worker.pending_count()}")


@app.command()
def smoke(
    task: str = typer.Option(
        "Turn this ambiguous supplied record into three grounded next steps without external tools.",
        help="Diagnostic task sent to an isolated temporary generated child agent",
    ),
    max_model_calls: int = typer.Option(3, min=1, max=6),
) -> None:
    """Diagnostic only: prove the generic Factory + Runtime path, not a hard-coded business."""
    with TemporaryDirectory(prefix="helis-agent-smoke-") as temporary:
        root = Path(temporary)
        engine = HelisEngine(HelisStore(root / "smoke.db"))
        opportunity = Opportunity(
            title="Generated agent runtime diagnostic",
            problem="A generated venture can require bounded reasoning over an ambiguous record.",
            customer="diagnostic venture",
            proposed_value="Produce a grounded structured next action.",
            stage=VentureStage.VALIDATED,
        )
        engine.store.save_opportunity(opportunity)
        validation = ValidationResult(
            run_id=uuid4(),
            experiment_id=uuid4(),
            opportunity_id=opportunity.id,
            outcome=ValidationOutcome.POSITIVE,
            confidence=1.0,
            summary="Diagnostic fixture only; no market claim is implied.",
            metrics={"smoke_fixture": 1.0},
            source="local_smoke_fixture",
        )
        engine.store.save_validation_result(validation)
        snapshot = architecture_input_hash(opportunity, [validation])
        capability = CapabilityNode(
            key="process_record",
            name="Process supplied record",
            goal="Turn an ambiguous supplied record into a grounded structured next action.",
            implementation=CapabilityImplementation.AI_AGENT,
            inputs=["supplied record"],
            outputs=["structured next action"],
            required_actions=[],
            success_metric="output is concise, structured and grounded only in supplied facts",
            rationale="The diagnostic requires language reasoning but no tools.",
            handles_customer_data=False,
            venture_isolation_required=True,
        )
        architecture = VentureArchitecture(
            opportunity_id=opportunity.id,
            input_hash=snapshot,
            capabilities=[capability],
            architecture_assumptions=["Diagnostic fixture only."],
        )
        VentureArchitectureStore(engine.store).save(architecture)
        spec = ChildAgentSpec(
            architecture_id=architecture.id,
            opportunity_id=opportunity.id,
            capability_key=capability.key,
            name=capability.name,
            goal=capability.goal,
            inputs=capability.inputs,
            outputs=capability.outputs,
            allowed_tools=[],
            memory_scope=AgentMemoryScope.NONE,
            constraints=["Use only facts present in the task.", "Do not claim external actions."],
            stop_conditions=["A concise grounded next action is produced."],
            success_metric=capability.success_metric,
            max_model_turns=max_model_calls,
            max_tool_calls_per_run=0,
            handles_customer_data=False,
            venture_isolation_required=True,
        )
        semantic = json.dumps(
            spec.model_dump(mode="json", exclude={"id"}),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")
        bundle = AgentSpecBundle(
            architecture_id=architecture.id,
            opportunity_id=opportunity.id,
            architecture_input_hash=snapshot,
            bundle_hash=hashlib.sha256(semantic).hexdigest(),
            agent_specs=[spec],
        )
        AgentSpecStore(engine.store).save(bundle)
        factory = ChildAgentFactory(engine, workspace_root=root / "ventures")
        report = factory.materialize_if_needed(opportunity.id)
        if report.blocked_reason is not None or len(report.artifacts) != 1:
            raise RuntimeError(report.blocked_reason or "unexpected diagnostic agent count")
        artifact = report.artifacts[0]
        console.print(f"agent={artifact.id} capability={artifact.capability_key}")
        result = ChildAgentRuntime(
            engine,
            OpenAICompatibleProvider.from_env(),
            CycleBudget(max_model_calls=max_model_calls, max_tokens=12_000, max_cost_cents=5.0),
            workspace_root=root / "ventures",
        ).run(artifact.id, task)
        console.print(
            f"status={result.status.value} turns={result.turns_used} stop={result.stop_reason}"
        )
        console.print(result.output)


if __name__ == "__main__":
    app()